FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html neurosonic_dashboard.html manifest.webmanifest robots.txt sitemap.xml llms.txt pwa-install.js service-worker.js og-neurosonic.svg /usr/share/nginx/html/
COPY icons /usr/share/nginx/html/icons
COPY .well-known /usr/share/nginx/html/.well-known
COPY docs /usr/share/nginx/html/docs

EXPOSE 80 443
