#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
NEUROSONIC SEO GENERATOR
Gjeneron automatikisht sitemap.xml, robots.txt dhe JSON-LD structured data
nga burimi i vetem i se vertetes: NeurosonicDNA / projekti.

Aligned with:
  - G001 Truth Law (Zero Fake: cdo gje rrjedh nga kodi, jo e shpikur)
  - G009 Knowledge Law (Unified, versioned, single source of truth)
"""

import os
import json
import datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
DOMAIN = "https://www.neurosonic.eu"


def _lastmod_for(path_rel):
    """Kthen dateshmërinë e fundit të modifikimit për një skedar relativ."""
    p = os.path.join(ROOT, path_rel.lstrip("/"))
    if os.path.isfile(p):
        return datetime.datetime.fromtimestamp(os.path.getmtime(p)).date().isoformat()
    return datetime.date.today().isoformat()


# ---------------------------------------------------------------------
# SITEMAP - faqet reale qe ekzistojne ne repo
# ---------------------------------------------------------------------
PAGES = [
    ("/", "daily", "1.0"),
    ("/index.html", "daily", "1.0"),
    ("/README.md", "weekly", "0.9"),
    ("/README.sq.md", "weekly", "0.9"),
    ("/NO_FAKE_POLICY.md", "monthly", "0.7"),
    ("/CONTRIBUTING.md", "monthly", "0.6"),
    ("/SECURITY.md", "monthly", "0.6"),
    ("/docs/Architecture.md", "monthly", "0.8"),
    ("/docs/Constitution.md", "monthly", "0.8"),
    ("/docs/CUDM.md", "monthly", "0.8"),
    ("/docs/community/ROADMAP.md", "monthly", "0.6"),
    ("/docs/legal/PRIVACY.md", "monthly", "0.7"),
    ("/docs/legal/LICENSE.md", "yearly", "0.5"),
    ("/docs/legal/CLA.md", "yearly", "0.5"),
    ("/docs/guides/zero-fake.md", "monthly", "0.8"),
    ("/docs/guides/hvo-memory.md", "monthly", "0.8"),
    ("/docs/guides/architecture.md", "monthly", "0.8"),
]

SITEMAP_HEADER = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
    'xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 '
    'http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n'
)


def generate_sitemap() -> str:
    lines = [SITEMAP_HEADER]
    for loc, freq, priority in PAGES:
        lines.append("  <url>")
        lines.append(f"    <loc>{DOMAIN}{loc}</loc>")
        lines.append(f"    <lastmod>{_lastmod_for(loc)}</lastmod>")
        lines.append(f"    <changefreq>{freq}</changefreq>")
        lines.append(f"    <priority>{priority}</priority>")
        lines.append("  </url>")
    lines.append("</urlset>\n")
    return "\n".join(lines)


# ---------------------------------------------------------------------
# ROBOTS.TXT
# ---------------------------------------------------------------------
ROBOTS = f"""# Neurosonic / Clisonix Trinity+ASI
# SEO Configuration - generated by neurosonic_seo.py

User-agent: *
Allow: /
Allow: /index.html
Allow: /docs/
Allow: /README.md
Allow: /README.sq.md
Allow: /NO_FAKE_POLICY.md
Allow: /CONTRIBUTING.md
Allow: /SECURITY.md
Allow: /sitemap.xml
Allow: /manifest.webmanifest
Disallow: /private/
Disallow: /logs/

# Sitemap
Sitemap: {DOMAIN}/sitemap.xml

# Crawl rate
Crawl-delay: 1

# Host
Host: {DOMAIN}
"""


# ---------------------------------------------------------------------
# JSON-LD FAQ structured data - Zero-Fake: rrjedh direkt nga DNA
# ---------------------------------------------------------------------
def generate_faq_schema() -> dict:
    """FAQ pages i bazuar ne Kushtetuten dhe arkitekturen reale."""
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "What is Neurosonic Trinity+ASI?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": (
                        "Neurosonic Trinity+ASI is a sovereign, modular AI operating "
                        "system with an immutable constitution, HVO memory "
                        "architecture, and built-in truth (Zero Fake) verification. "
                        "It prioritizes user ownership of data, distributed nodes, "
                        "zero-trust security, and human oversight."
                    ),
                },
            },
            {
                "@type": "Question",
                "name": "How does Neurosonic guarantee Zero Fake?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": (
                        "Neurosonic guarantees Zero Fake through source verification "
                        "(every fact has a verifiable source), hash verification "
                        "(every response carries a hash), and a multi-step validator "
                        "pipeline that validates all outputs before delivery "
                        "(Constitution G001 Truth Law and QR001-QR005 quality rules)."
                    ),
                },
            },
            {
                "@type": "Question",
                "name": "What is HVO Memory in Neurosonic?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": (
                        "HVO (Horizontal, Vertical, Orbital) Memory is Neurosonic's "
                        "memory architecture. It also includes Resonance, Film, "
                        "Stigma, Working, and Long Term memory types, storing "
                        "information across breadth, depth, and time-aware "
                        "relationships (Memory rules MR001-MR006)."
                    ),
                },
            },
            {
                "@type": "Question",
                "name": "Who owns the data in Neurosonic?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": (
                        "Users own their data and identity. Neurosonic follows the "
                        "User Ownership Law (G003): data is encrypted, stored under "
                        "zero-trust, and users can export or delete their data "
                        "anytime. Data is never shared without explicit consent "
                        "(Data rules DR001-DR005)."
                    ),
                },
            },
            {
                "@type": "Question",
                "name": "Does Neurosonic have external dependencies?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": (
                        "No. Neurosonic is built on the Internal Infrastructure Law "
                        "(G004) and Sovereignty Law (G002): core components are "
                        "built internally with zero vendor lock-in and zero external "
                        "dependencies. The system is capable of running offline."
                    ),
                },
            },
        ],
    }


# ---------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------
def main() -> None:
    # Sitemap
    sitemap_path = os.path.join(ROOT, "sitemap.xml")
    with open(sitemap_path, "w", encoding="utf-8") as f:
        f.write(generate_sitemap())
    print(f"✅ Generated {sitemap_path}")

    # Robots
    robots_path = os.path.join(ROOT, "robots.txt")
    with open(robots_path, "w", encoding="utf-8") as f:
        f.write(ROBOTS)
    print(f"✅ Generated {robots_path}")

    # FAQ schema preview (nje shembull per testim/integration)
    print("\n📄 FAQ JSON-LD preview:")
    print(json.dumps(generate_faq_schema(), indent=2))


if __name__ == "__main__":
    main()
