#!/usr/bin/env python3
"""Neurosonic UI Designer: local-first panel generation and profile storage."""

from __future__ import annotations

import hashlib
import json
import os
import time
from typing import Any


class PersonalNodeStore:
    """Ruajtje lokale e profileve të UI për çdo përdorues/node."""

    def __init__(self, root_dir: str = "personal_node/profiles"):
        self.root_dir = os.path.abspath(root_dir)
        os.makedirs(self.root_dir, exist_ok=True)

    def _profile_path(self, profile_id: str) -> str:
        safe_id = "".join(ch for ch in profile_id if ch.isalnum() or ch in {"-", "_"})
        safe_id = safe_id or "default"
        return os.path.join(self.root_dir, f"{safe_id}.json")

    def save_profile(self, profile_id: str, schema: dict[str, Any]) -> dict[str, Any]:
        path = self._profile_path(profile_id)
        payload = {
            "profile_id": profile_id,
            "updated_at": time.time(),
            "schema": schema,
            "schema_hash": hashlib.sha256(
                json.dumps(schema, sort_keys=True, ensure_ascii=False).encode("utf-8")
            ).hexdigest(),
        }
        with open(path, "w", encoding="utf-8") as file:
            json.dump(payload, file, ensure_ascii=False, indent=2)

        return {"profile_id": profile_id, "path": path, "hash": payload["schema_hash"]}

    def load_profile(self, profile_id: str) -> dict[str, Any] | None:
        path = self._profile_path(profile_id)
        if not os.path.exists(path):
            return None

        with open(path, "r", encoding="utf-8") as file:
            return json.load(file)

    def list_profiles(self) -> list[dict[str, Any]]:
        profiles: list[dict[str, Any]] = []
        for file_name in os.listdir(self.root_dir):
            if not file_name.endswith(".json"):
                continue
            path = os.path.join(self.root_dir, file_name)
            try:
                with open(path, "r", encoding="utf-8") as file:
                    data = json.load(file)
                profiles.append(
                    {
                        "profile_id": data.get("profile_id", file_name[:-5]),
                        "updated_at": data.get("updated_at"),
                        "schema_hash": data.get("schema_hash", ""),
                    }
                )
            except (json.JSONDecodeError, OSError):
                continue

        profiles.sort(key=lambda item: item.get("updated_at", 0), reverse=True)
        return profiles


class UIDesignEngine:
    """Gjeneron një panel dinamik nga prompt-i i përdoruesit."""

    def generate_schema(
        self,
        prompt: str,
        preferences: dict[str, Any] | None = None,
        owner_id: str = "local-user",
    ) -> dict[str, Any]:
        preferences = preferences or {}
        detected_mode = self._detect_mode(prompt)
        theme = self._build_theme(preferences)
        widgets = self._build_widgets(prompt, detected_mode, preferences)

        return {
            "schema_version": "1.0",
            "owner_id": owner_id,
            "title": preferences.get("title", "My Neurosonic Panel"),
            "description": prompt.strip() or "Generated by Neurosonic UI Designer",
            "mode": detected_mode,
            "theme": theme,
            "layout": {
                "type": preferences.get("layout_type", "grid"),
                "columns": int(preferences.get("columns", 12)),
                "gap": int(preferences.get("gap", 16)),
            },
            "widgets": widgets,
            "actions": [
                {"id": "refresh", "label": "Refresh", "type": "api_call"},
                {"id": "save_layout", "label": "Save Layout", "type": "local_save"},
            ],
            "generated_at": time.time(),
        }

    def _detect_mode(self, prompt: str) -> str:
        text = prompt.lower()
        if any(token in text for token in ["image", "vision", "ocr", "scan", "foto"]):
            return "vision"
        if any(token in text for token in ["governance", "audit", "policy", "compliance"]):
            return "reasoning"
        if any(token in text for token in ["code", "debug", "developer", "api"]):
            return "code"
        return "text"

    def _build_theme(self, preferences: dict[str, Any]) -> dict[str, Any]:
        palette = preferences.get("palette", "neon-night")
        density = preferences.get("density", "comfortable")
        return {
            "palette": palette,
            "density": density,
            "font": preferences.get("font", "Inter"),
            "radius": preferences.get("radius", 12),
        }

    def _build_widgets(
        self, prompt: str, mode: str, preferences: dict[str, Any]
    ) -> list[dict[str, Any]]:
        widgets: list[dict[str, Any]] = [
            {
                "id": "welcome",
                "type": "hero",
                "title": preferences.get("hero_title", "Welcome Creator"),
                "subtitle": "Design your personal UI node",
                "span": {"col": 12, "row": 1},
            },
            {
                "id": "activity",
                "type": "timeline",
                "title": "Activity",
                "source": "/api/lightning/stats",
                "span": {"col": 6, "row": 2},
            },
            {
                "id": "health",
                "type": "status",
                "title": "System Health",
                "source": "/api/health",
                "span": {"col": 6, "row": 2},
            },
        ]

        if mode == "vision":
            widgets.append(
                {
                    "id": "vision_input",
                    "type": "image-dropzone",
                    "title": "Vision Input",
                    "action": "/api/lightning/scan",
                    "span": {"col": 12, "row": 2},
                }
            )
        elif mode == "reasoning":
            widgets.append(
                {
                    "id": "policy_matrix",
                    "type": "policy-grid",
                    "title": "Governance Matrix",
                    "source": "/api/dna",
                    "span": {"col": 12, "row": 2},
                }
            )
        elif mode == "code":
            widgets.append(
                {
                    "id": "api_console",
                    "type": "console",
                    "title": "API Console",
                    "action": "/api/shell/think",
                    "span": {"col": 12, "row": 2},
                }
            )
        else:
            widgets.append(
                {
                    "id": "notes",
                    "type": "markdown",
                    "title": "Personal Notes",
                    "content": prompt[:500],
                    "span": {"col": 12, "row": 2},
                }
            )

        return widgets
